
import { GoogleGenAI, GenerateContentResponse } from "@google/genai";
import { BrandSettings } from "../types";

export const generateOgImage = async (settings: BrandSettings): Promise<string> => {
  // Ensure we get a fresh instance to pick up the selected API key
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  const prompt = `
Create an OG image for your website with Nano Banana Pro:

Create a premium open-graph hero image for ${settings.name}:

A wide horizontal layout (16:9 ratio) designed for social sharing, website headers, and marketing collateral. This is a high-end designer mockup presentation suitable for a branding portfolio or product launch. The focus is on clarity, balance, negative space and visual confidence.

LAYOUT STRUCTURE:

The composition is split into two clear zones with generous breathing room between them.

LEFT ZONE:
The ${settings.name} logo and brand name are placed in the top-left corner. The logo is sized appropriately for the format, not too large, not too small. It reads clearly but doesn't dominate.

Below the logo, a single large headline is set in a clean, modern sans-serif typeface. The headline is: "${settings.headline}". It is confident, left-aligned, and sits comfortably within the left third of the canvas. The text color is derived from the brand palette (specifically using ${settings.primaryColor}).

RIGHT ZONE:
One floating, rounded rectangular panel suggesting a product interface, dashboard, or app screen. The panel has subtle depth, either through a soft drop shadow or slight elevation effect. The contents of the panel are suggestive rather than detailed, hinting at functionality without clutter.

The panel is angled very slightly or presented straight-on depending on what feels most balanced. It floats naturally in the composition, grounded by its shadow but with clear separation from the background.

NEGATIVE SPACE:
Strong use of negative space throughout. The background is clean and uncluttered. There is clear visual breathing room between the left text block and the right interface panel. Nothing feels cramped or crowded.

COLOR & STYLE:
Colors are drawn directly from the brand palette. Use ${settings.primaryColor} as the primary accent color. The background should be clean, perhaps an off-white or a very subtle gradient that complements ${settings.primaryColor}.

The overall style is flat or near-flat. No heavy gradients, no glossy effects, no 3D renders. Shadows are subtle and serve only to create gentle depth. Typography is modern, confident, and legible at small sizes.

MOOD & FEEL:
Clean SaaS homepage hero. Quiet confidence. The image should feel premium, polished and intentional. Every element is placed with purpose. The overall impression is of a company that knows what it's doing.

WHAT TO AVOID:
No stock photo elements. No people. No complex illustrations. No decorative graphics or patterns. No multiple interface panels. No visual noise. No text other than the headline and brand name. No borders or frames around the image.

OUTPUT:
A single 16:9 image with no watermarks, no mockup frames, and no external branding. Ready to use as an open-graph image, social header, or presentation slide.
`.trim();

  try {
    const parts: any[] = [{ text: prompt }];
    
    // Add logo as inline data if provided to guide the model's design
    if (settings.logoBase64 && settings.logoMimeType) {
      parts.push({
        inlineData: {
          mimeType: settings.logoMimeType,
          data: settings.logoBase64
        }
      });
    }

    const response: GenerateContentResponse = await ai.models.generateContent({
      model: 'gemini-3-pro-image-preview',
      contents: { parts },
      config: {
        imageConfig: {
          aspectRatio: "16:9",
          imageSize: "1K" // Using 1K for speed, but model supports up to 4K
        }
      },
    });

    let imageUrl = '';
    
    // Nano Banana response handling
    if (response.candidates?.[0]?.content?.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          imageUrl = `data:image/png;base64,${part.inlineData.data}`;
          break;
        }
      }
    }

    if (!imageUrl) {
      throw new Error("No image was generated by the model.");
    }

    return imageUrl;
  } catch (error: any) {
    if (error?.message?.includes("Requested entity was not found")) {
      // Per instructions: reset key selection if error occurs
      if (window.aistudio) {
        await window.aistudio.openSelectKey();
      }
    }
    throw error;
  }
};
